trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'abdulrahmanhadz/aicore-devops-pipeline'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'v0.0.1'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Abdulrahman Al Haddad DevOps(23d74b9b-d720-485c-8f03-1821e7fb48d3)'
    azureResourceGroup: 'cloud-shell-storage-westeurope'
    kubernetesCluster: 'Abdulrahman-AiCore-AKS'
    manifests: 'application-manifest.yaml'